spring.application.name=webdev
server.port=8080

# Imports environment variables from .env file
spring.config.import=optional:file:.env[.properties]

# DataSource
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update

#Limpa a base de dados a cada inicianlização
spring.jpa.hibernate.ddl-auto=create

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
